uploads = []

[[generated]]
id = "0hFsN8Z864LhnCXr4xkeY"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "anime waist belly icon"

[[generated]]
id = "T2E51skFt2Tjlgs51YgR8"
uri = "file://artifacts/mobile/assets/images/character.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VYDMMGqqVtBWfB5AAeBV4"
uri = "file://artifacts/mobile/assets/images/intestines.png"
type = "image"
title = "generated_image"

[[generated]]
id = "btG_vHj5RLjKF0VZea_6X"
uri = "file://artifacts/mobile/assets/images/cavity_bg.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NujjVOGzJlouQZXj_nCnE"
uri = "file://artifacts/mobile/assets/images/belly_external.png"
type = "image"
title = "demon character belly external"

[[generated]]
id = "QIbM6USZgk_TP3_PES8YT"
uri = "file://artifacts/mobile/assets/images/strike_fist.png"
type = "image"
title = "strike fist tool"

[[generated]]
id = "jjrvzgp43boAMyUYwkpcS"
uri = "file://artifacts/mobile/assets/images/strike_bat.png"
type = "image"
title = "baseball bat tool"

[[generated]]
id = "-WabusgCuRnOTkAIYXN2K"
uri = "file://artifacts/mobile/assets/images/strike_hammer.png"
type = "image"
title = "bell hammer tool"

[[outputs]]
id = "EvFH6bgGV0eFpaLTc_px6"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "新图标 — 女主角腰腹"
