uploads = []
outputs = []

[[generated]]
id = "0hFsN8Z864LhnCXr4xkeY"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "T2E51skFt2Tjlgs51YgR8"
uri = "file://artifacts/mobile/assets/images/character.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VYDMMGqqVtBWfB5AAeBV4"
uri = "file://artifacts/mobile/assets/images/intestines.png"
type = "image"
title = "generated_image"

[[generated]]
id = "btG_vHj5RLjKF0VZea_6X"
uri = "file://artifacts/mobile/assets/images/cavity_bg.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NujjVOGzJlouQZXj_nCnE"
uri = "file://artifacts/mobile/assets/images/belly_external.png"
type = "image"
title = "demon character belly external"
